---
title: 'STA 602 Homework and Lab Template'
author: "William Tirone"
date: "`r format(Sys.time(), '%d %B, %Y')`"
output:
  pdf_document: default
---


```{r setup, message=F, warning=F, echo=F}
library(tidyverse)
library(ggplot2)
require(magrittr)
require(plyr)
ggplot2::theme_set(ggplot2::theme_bw())
knitr::opts_chunk$set(fig.align = 'center')
```

### Exercise 1
```{r}
data <- read.table(file = url("http://www2.stat.duke.edu/~pdh10/FCBS/Exercises/azdiabetes.dat"),header=TRUE)
head(data)
```
### Exercise 2

```{r}
seq2 = seq(from=0,to=1,by=.01)
seq2
```

### Exercise 3

```{r}
seq3 <- seq(from = -3, to = 3, by = .5)
sort(seq3,decreasing=TRUE)
```

### Exercise 4

```{r}
mat5 <- matrix(seq(1,100,1), nrow = 4, ncol = 25, byrow = T)
apply(X = mat5, MARGIN = 1, FUN =var)
```

### Exercise 5 

```{r}
W = rbeta(500,.5,.5)
```

### Exercise 6
```{r}
colnames(data)
```

Not looking too interesting below yet.
```{r}
ggplot(data,aes(glu,npreg)) + geom_point()
```
Let's try another plot: 
```{r}
ggplot(data,aes(diabetes,age)) + geom_bin2d()
```

```{r}
ggplot(data,aes(bp,age)) + geom_point(color='red')
```